name: plant_monitor_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2
  image_picker: ^0.8.7+5

  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ðŸ”¥ Add flutter_launcher_icons package
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  # ðŸ”¥ Add this asset folder (your GrowMate icon)
  assets:
    - assets/icon/
    - assets/images/plant.png
    - assets/images/aloe_vera.png
    - assets/images/rose.png
    - assets/images/cactus.png
    - assets/images/perennial.png



# ðŸ”¥ Launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/growmate.png"
  adaptive_icon_foreground: "assets/icon/growmate.png"
  adaptive_icon_background: "#4CAF50"     # green background (you can change)
